# Generated by Django 4.2.7 on 2026-07-02 19:32

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(default=main.models.generate_order_number, max_length=20, unique=True, verbose_name='Номер'),
        ),
    ]
