# Generated by Django 4.2.7 on 2026-07-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_is_paid_order_is_warranty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxuserlink',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон в Max'),
        ),
    ]
