# Generated by Django 4.2.7 on 2026-07-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_maxuserlink_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='max_linked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Max привязан'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_user_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Max user ID'),
        ),
    ]
