# Generated by Django 4.2.7 on 2026-07-06 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_add_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Номер сметы')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено клиенту'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('in_work', 'В работе'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка общая (%)')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Комиссионные (%)')),
                ('dealer_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Дилерская наценка (%)')),
                ('unexpected_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Непредвиденные расходы (₽)')),
                ('delivery_type', models.CharField(choices=[('client', 'Самовывоз'), ('our', 'Наша доставка'), ('tc', 'Транспортная компания'), ('none', 'Не требуется')], default='client', max_length=10, verbose_name='Тип доставки')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки (₽)')),
                ('tax_type', models.CharField(choices=[('usn', 'УСН (доходы)'), ('usn_dr', 'УСН (доходы-расходы)'), ('osno', 'ОСНО (с НДС)'), ('patent', 'Патент'), ('none', 'Без налога')], default='usn', max_length=10, verbose_name='Система налогообложения')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=6, max_digits=5, verbose_name='Ставка налога (%)')),
                ('employee', models.CharField(blank=True, max_length=200, verbose_name='Ответственный сотрудник')),
                ('employee_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон сотрудника')),
                ('total_materials', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого материалы')),
                ('total_services', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого услуги')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Подытог')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого себестоимость')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прибыль')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='main.client', verbose_name='Клиент (контрагент)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Смета/КП',
                'verbose_name_plural': 'Сметы и КП',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование услуги')),
                ('category', models.CharField(choices=[('installation', 'Монтаж'), ('setup', 'Настройка/Пусконаладка'), ('design', 'Проектирование'), ('maintenance', 'Обслуживание/ТО'), ('repair', 'Ремонт'), ('consulting', 'Консультация'), ('other', 'Другое')], default='installation', max_length=30, verbose_name='Категория')),
                ('unit', models.CharField(default='шт', max_length=30, verbose_name='Единица измерения')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена для клиента')),
                ('installer_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зарплата монтажникам')),
                ('notes', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги и работы',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название организации')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое название')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('legal_address', models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(blank=True, max_length=500, verbose_name='Фактический адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, max_length=300, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт')),
                ('settlement_account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Директор')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('material', 'Материал со склада'), ('service', 'Услуга из справочника'), ('custom_material', 'Произвольный материал'), ('custom_service', 'Произвольная услуга/работа')], max_length=20, verbose_name='Тип позиции')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('unit', models.CharField(default='шт', max_length=30, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость за ед.')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за ед.')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка на позицию (%)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('installer_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ЗП монтажникам')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.commercialestimate', verbose_name='Смета')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.inventoryitem', verbose_name='Позиция склада')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.estimateservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Позиция сметы',
                'verbose_name_plural': 'Позиции сметы',
                'ordering': ['order_num', 'id'],
            },
        ),
        migrations.AddField(
            model_name='commercialestimate',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.legalentity', verbose_name='Юрлицо (наша компания)'),
        ),
        migrations.AddField(
            model_name='commercialestimate',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='main.order', verbose_name='Связанная заявка'),
        ),
    ]
