# Generated by Django 4.2.7 on 2026-07-07 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_client_director_name_client_inn_client_is_legal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('legal_address', models.CharField(blank=True, max_length=500, verbose_name='Юр. адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Номер накладной')),
                ('invoice_date', models.DateField(verbose_name='Дата накладной')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('received', 'Принято полностью'), ('partial', 'Принято частично'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приёмки')),
                ('total_ordered', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Заказано на сумму')),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Принято на сумму')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='main.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Накладная поставщика',
                'verbose_name_plural': 'Накладные поставщиков',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, help_text='Сканируется с упаковки товара', max_length=100, null=True, unique=True, verbose_name='Штрих-код (SKU)'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='supply_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='main.supplyinvoice', verbose_name='Накладная'),
        ),
        migrations.CreateModel(
            name='SupplyInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField(default=0, verbose_name='Заказано')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Принято')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ед.')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_items', to='main.inventoryitem', verbose_name='Номенклатура')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.supplyinvoice', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Позиция накладной',
                'verbose_name_plural': 'Позиции накладной',
                'unique_together': {('invoice', 'inventory_item')},
            },
        ),
    ]
