# Generated by Django 4.2.7 on 2026-07-09 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_add_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErcAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Номер лицевого счета')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('residents_count', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Кол-во жильцов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'ЕРЦ — лицевой счёт',
                'verbose_name_plural': 'ЕРЦ — лицевые счета',
                'ordering': ['account_number'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='entrance_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='№ парадной/подъезда'),
        ),
        migrations.AddField(
            model_name='client',
            name='management_company',
            field=models.CharField(blank=True, max_length=300, verbose_name='Управляющая компания/ТСЖ'),
        ),
        migrations.AddField(
            model_name='client',
            name='personal_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер лицевого счета'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='ErcBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Например: 2026-05-01 для мая 2026', verbose_name='Период (первое число месяца)')),
                ('balance_start', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сальдо на начало')),
                ('charged', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Начислено (фактически)')),
                ('charged_no_benefits', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Начислено (без льгот)')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплачено')),
                ('paid_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% оплаты')),
                ('balance_end', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сальдо на конец (дебет)')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Кредит')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='main.ercaccount', verbose_name='Лицевой счёт')),
            ],
            options={
                'verbose_name': 'ЕРЦ — платёжная запись',
                'verbose_name_plural': 'ЕРЦ — платёжные записи',
                'ordering': ['-period', 'account__account_number'],
                'unique_together': {('account', 'period')},
            },
        ),
    ]
