# Generated by Django 4.2.7 on 2026-07-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_add_erc_and_client_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ercbillingrecord',
            name='balance_end',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сальдо на конец (дебет)'),
        ),
        migrations.AlterField(
            model_name='ercbillingrecord',
            name='balance_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сальдо на начало'),
        ),
        migrations.AlterField(
            model_name='ercbillingrecord',
            name='charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Начислено (фактически)'),
        ),
        migrations.AlterField(
            model_name='ercbillingrecord',
            name='charged_no_benefits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Начислено (без льгот)'),
        ),
        migrations.AlterField(
            model_name='ercbillingrecord',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Кредит'),
        ),
        migrations.AlterField(
            model_name='ercbillingrecord',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='ercbillingrecord',
            name='paid_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='% оплаты'),
        ),
    ]
