# Generated by Django 4.2.7 on 2026-07-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_fix_erc_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('manual', 'Ручной ввод'), ('excel_import', 'Импорт Excel (ТСЖ)'), ('erc', 'ЕРЦ')], default='manual', max_length=20, verbose_name='Источник'),
        ),
    ]
