# Generated by Django 4.2.7 on 2026-07-10 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0033_add_storage_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер УПД')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата составления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выдано'), ('cancelled', 'Аннулировано')], default='draft', max_length=20, verbose_name='Статус')),
                ('basis', models.CharField(blank=True, help_text='Договор, счёт, заявка', max_length=500, verbose_name='Основание')),
                ('received_by_name', models.CharField(blank=True, help_text='Кто принял товар со стороны получателя', max_length=200, verbose_name='Принял (ФИО)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма итого')),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='В т.ч. НДС')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('from_legal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_invoices', to='main.legalentity', verbose_name='От юр. лица')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
                ('to_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_invoices', to='main.client', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Исходящая накладная (УПД)',
                'verbose_name_plural': 'Исходящие накладные (УПД)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ед.')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('vat_rate', models.CharField(blank=True, default='20%', max_length=5, verbose_name='Ставка НДС')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_items', to='main.inventoryitem', verbose_name='Номенклатура')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.outgoinginvoice', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Позиция УПД',
                'verbose_name_plural': 'Позиции УПД',
            },
        ),
    ]
