# Generated by Django 4.2.7 on 2026-07-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_fix_outgoinginvoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='bitrix24_active',
            field=models.BooleanField(default=False, verbose_name='Интеграция с Битрикс24 активна'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bitrix24_webhook',
            field=models.CharField(blank=True, help_text='Входящий вебхук: https://yourdomain.bitrix24.ru/rest/1/xxxx...', max_length=500, verbose_name='Bitrix24 Webhook URL'),
        ),
    ]
