# Generated by Django 4.2.7 on 2026-07-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_fix_client_address_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='rostelecom_account_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Account ID Ростелеком'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='rostelecom_active',
            field=models.BooleanField(default=False, verbose_name='Интеграция с Ростелеком АТС активна'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='rostelecom_api_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='API токен Ростелеком'),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True, verbose_name='ID звонка')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('direction', models.CharField(choices=[('incoming', 'Входящий'), ('outgoing', 'Исходящий'), ('internal', 'Внутренний')], max_length=20, verbose_name='Направление')),
                ('start_time', models.DateTimeField(verbose_name='Начало звонка')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('call_type', models.CharField(choices=[('voip', 'VoIP'), ('mobile', 'Мобильный'), ('landline', 'Стационарный'), ('unknown', 'Неизвестно')], default='unknown', max_length=20, verbose_name='Тип звонка')),
                ('status', models.CharField(choices=[('completed', 'Завершен'), ('missed', 'Пропущенный'), ('busy', 'Занято'), ('failed', 'Ошибка'), ('queued', 'В очереди')], default='completed', max_length=20, verbose_name='Статус')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Полные данные (JSON)')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Синхронизировано')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='main.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Звонок (Ростелеком)',
                'verbose_name_plural': 'Журнал звонков (Ростелеком)',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['phone', 'start_time'], name='main_calllo_phone_55dce6_idx'), models.Index(fields=['client', 'start_time'], name='main_calllo_client__300ae6_idx')],
            },
        ),
    ]
