# Generated by Django 4.2.7 on 2026-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_building_systems_and_mc_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='legal_type',
            field=models.CharField(blank=True, choices=[('uk_tszh', 'УК / ТСЖ'), ('developer', 'Застройщик'), ('contractor', 'Подрядчик'), ('partner', 'Партнёр'), ('independent', 'Самостоятельное'), ('other', 'Другое')], max_length=30, verbose_name='Тип юрлица'),
        ),
    ]
