# Generated by Django 4.2.7 on 2026-07-19 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0050_client_legal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompany',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма договора в мес.'),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='№ договора'),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='На обслуживании'),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='terminated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расторжения'),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='termination_reason',
            field=models.TextField(blank=True, verbose_name='Причина расторжения'),
        ),
        migrations.CreateModel(
            name='MCContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('management_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.managementcompany')),
            ],
            options={
                'verbose_name': 'Контакт УК',
                'verbose_name_plural': 'Контакты УК',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MCComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('call', 'Звонок'), ('email', 'Письмо'), ('complaint', 'Жалоба'), ('request', 'Запрос'), ('meeting', 'Встреча'), ('note', 'Заметка')], default='note', max_length=30)),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('management_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.managementcompany')),
            ],
            options={
                'verbose_name': 'Комментарий УК',
                'verbose_name_plural': 'Комментарии УК',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период (месяц)')),
                ('amount_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Начислено')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплачено')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено бухгалтером')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('management_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.managementcompany')),
            ],
            options={
                'verbose_name': 'Платёж УК',
                'verbose_name_plural': 'Платежи УК',
                'ordering': ['-period'],
                'unique_together': {('management_company', 'period')},
            },
        ),
    ]
