# Generated by Django 4.2.7 on 2026-07-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_apartment_order_building_number_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='api_base_url',
            field=models.CharField(default='/api', max_length=255, verbose_name='API base URL'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dadata_secret',
            field=models.CharField(blank=True, max_length=200, verbose_name='DaData секретный ключ'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dadata_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='DaData API токен'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dns_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='DNS-имя'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='external_ip',
            field=models.CharField(default='83.243.73.86', max_length=50, verbose_name='Внешний IP'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='external_port',
            field=models.PositiveIntegerField(default=3000, verbose_name='Внешний порт'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='internal_ip',
            field=models.CharField(default='192.168.1.38', max_length=50, verbose_name='Внутренний IP'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='internal_port',
            field=models.PositiveIntegerField(default=8000, verbose_name='Внутренний порт'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_api_url',
            field=models.CharField(default='https://business.max.ru', max_length=255, verbose_name='Max API URL'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_bot_active',
            field=models.BooleanField(default=False, verbose_name='Max бот активен'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_bot_name',
            field=models.CharField(default='CRM Bot', max_length=100, verbose_name='Max бот имя'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_bot_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Max бот токен'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='traccar_active',
            field=models.BooleanField(default=False, verbose_name='Traccar активен'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='traccar_pass',
            field=models.CharField(blank=True, max_length=100, verbose_name='Traccar пароль'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='traccar_url',
            field=models.CharField(default='http://localhost:8082', max_length=255, verbose_name='Traccar URL'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='traccar_user',
            field=models.CharField(blank=True, max_length=100, verbose_name='Traccar логин'),
        ),
    ]
