# Generated by Django 4.2.7 on 2026-07-05 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_add_inventory_and_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='helpers',
            field=models.ManyToManyField(blank=True, related_name='helper_orders', to=settings.AUTH_USER_MODEL, verbose_name='Помощники'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.master', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('repair', 'Ремонт'), ('sale', 'Продажа оборудования'), ('maintenance', 'Сервисное ТО'), ('installation', 'Монтаж оборудования'), ('contract_install', 'Договор на монтаж'), ('contract_service', 'Договор на обслуживание'), ('inspection', 'Обследование'), ('connection', 'Подключение')], max_length=20, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('dispatcher', 'Диспетчер'), ('master', 'Мастер'), ('installer', 'Монтажник'), ('engineer', 'Инженер'), ('chief_engineer', 'Главный инженер'), ('supervisor', 'Начальник сервисной службы'), ('tech_director', 'Технический директор'), ('executive_director', 'Исполнительный директор'), ('general_director', 'Генеральный директор')], default='master', max_length=30, verbose_name='Роль'),
        ),
    ]
