# Generated by Django 4.2.7 on 2026-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_add_client_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='personal_account_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Номер лицевого счета'),
        ),
    ]
