# Generated by Django 4.2.7 on 2026-07-10 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_fix_vat_rate_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoinginvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата составления'),
        ),
    ]
