# Generated by Django 4.2.7 on 2026-07-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('street_type', models.CharField(choices=[('street', 'Улица'), ('avenue', 'Проспект'), ('lane', 'Переулок'), ('boulevard', 'Бульвар'), ('highway', 'Шоссе'), ('square', 'Площадь'), ('embankment', 'Набережная'), ('passage', 'Проезд'), ('alley', 'Аллея'), ('microdistrict', 'Микрорайон'), ('other', 'Другое')], default='street', max_length=20, verbose_name='Тип улицы')),
                ('street_name', models.CharField(max_length=200, verbose_name='Название улицы')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('building_number', models.CharField(blank=True, max_length=20, verbose_name='Корпус/строение')),
                ('apartments_count', models.PositiveIntegerField(default=0, verbose_name='Количество квартир')),
                ('entrances_count', models.PositiveIntegerField(default=1, verbose_name='Количество подъездов')),
                ('equipment_type', models.CharField(blank=True, choices=[('intercom', 'Домофон'), ('video_intercom', 'Видеодомофон'), ('camera', 'Камера'), ('call_panel', 'Вызывная панель'), ('door_lock', 'Дверной замок'), ('multi_apartment', 'Многоквартирная система'), ('other', 'Другое')], max_length=30, verbose_name='Тип оборудования')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='main.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ['city', 'street_name', 'house_number'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.building', verbose_name='Дом'),
        ),
    ]
