# Generated by Django 4.2.7 on 2026-07-02 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_accepted_at_order_cost_order_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraccarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(help_text='Например: http://traccar.example.com:8082', max_length=255, verbose_name='URL сервера')),
                ('username', models.CharField(max_length=100, verbose_name='Логин (email)')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=False, verbose_name='Интеграция активна')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=5, verbose_name='Интервал синхронизации (мин)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки Traccar',
                'verbose_name_plural': 'Настройки Traccar',
            },
        ),
        migrations.CreateModel(
            name='TraccarMileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(default=0, verbose_name='Пробег (км)')),
                ('start_position_lat', models.FloatField(blank=True, null=True, verbose_name='Старт: широта')),
                ('start_position_lon', models.FloatField(blank=True, null=True, verbose_name='Старт: долгота')),
                ('end_position_lat', models.FloatField(blank=True, null=True, verbose_name='Финиш: широта')),
                ('end_position_lon', models.FloatField(blank=True, null=True, verbose_name='Финиш: долгота')),
                ('data', models.JSONField(default=dict, verbose_name='Данные пробега (JSON)')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Синхронизировано')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileages', to='main.master', verbose_name='Мастер')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='main.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Пробег по заявке',
                'verbose_name_plural': 'Пробеги по заявкам',
            },
        ),
        migrations.CreateModel(
            name='TraccarDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.PositiveIntegerField(unique=True, verbose_name='ID устройства в Traccar')),
                ('device_name', models.CharField(blank=True, max_length=200, verbose_name='Название устройства')),
                ('last_latitude', models.FloatField(blank=True, null=True, verbose_name='Последняя широта')),
                ('last_longitude', models.FloatField(blank=True, null=True, verbose_name='Последняя долгота')),
                ('last_speed', models.FloatField(blank=True, null=True, verbose_name='Последняя скорость (км/ч)')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление координат')),
                ('is_online', models.BooleanField(default=False, verbose_name='Устройство онлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Привязано')),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traccar_device', to='main.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'GPS-устройство мастера',
                'verbose_name_plural': 'GPS-устройства мастеров',
            },
        ),
    ]
