# Generated by Django 4.2.7 on 2026-07-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_traccarsettings_traccarmileage_traccardevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traccardevice',
            name='device_id',
        ),
        migrations.AddField(
            model_name='traccardevice',
            name='internal_device_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='Внутренний ID устройства в Traccar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traccardevice',
            name='unique_id',
            field=models.CharField(default='0', max_length=100, unique=True, verbose_name='Уникальный ID (IMEI)'),
            preserve_default=False,
        ),
    ]
