# Generated by Django 4.2.7 on 2026-07-03 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_traccardevice_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup', models.BooleanField(default=False, verbose_name='Авто-бэкап')),
                ('backup_time', models.CharField(default='03:00', max_length=5, verbose_name='Время бэкапа')),
                ('backup_keep_days', models.PositiveIntegerField(default=30, verbose_name='Хранить дней')),
                ('backup_path', models.CharField(default='/var/backups/crm/', max_length=255, verbose_name='Путь для бэкапов')),
                ('media_max_size_mb', models.PositiveIntegerField(default=50, verbose_name='Макс. размер файла (МБ)')),
                ('media_allowed_types', models.CharField(default='jpg,jpeg,png,mp4,mov,avi', max_length=200, verbose_name='Разрешённые типы')),
                ('media_storage_path', models.CharField(default='/var/media/crm/', max_length=255, verbose_name='Путь хранения')),
                ('media_retention_days', models.PositiveIntegerField(default=90, verbose_name='Хранить дней')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Системные настройки',
                'verbose_name_plural': 'Системные настройки',
            },
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='master_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта мастера'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='master_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота мастера'),
        ),
        migrations.CreateModel(
            name='OrderMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/%Y/%m/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], max_length=10, verbose_name='Тип')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.order', verbose_name='Заявка')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Медиа заявки',
                'verbose_name_plural': 'Медиа заявок',
            },
        ),
    ]
