# Generated by Django 4.2.7 on 2026-07-03 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_systemsettings_orderhistory_master_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждена'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('assigned', 'Назначена'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('paused', 'На паузе'), ('need_help', 'Требуется помощь'), ('completed', 'Выполнена'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Начало смены')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец смены')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('orders_total', models.PositiveIntegerField(default=0, verbose_name='Заявок за смену')),
                ('orders_completed', models.PositiveIntegerField(default=0, verbose_name='Выполнено')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая стоимость')),
                ('total_mileage_km', models.FloatField(default=0, verbose_name='Пробег (км)')),
                ('hours_worked', models.FloatField(default=0, verbose_name='Часов на смене')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рабочая смена',
                'verbose_name_plural': 'Рабочие смены',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('dispatcher', 'Диспетчер'), ('master', 'Мастер')], default='master', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_on_shift', models.BooleanField(default=False, verbose_name='На смене')),
                ('shift_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Смена начата')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
