# Generated by Django 4.2.7 on 2026-07-04 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_push_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=255, verbose_name='Токен бота')),
                ('bot_name', models.CharField(default='CRM Bot', max_length=100, verbose_name='Имя бота')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('api_base_url', models.CharField(default='https://business.max.ru', max_length=255, verbose_name='API URL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки Max бота',
                'verbose_name_plural': 'Настройки Max ботов',
            },
        ),
        migrations.CreateModel(
            name='MaxUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user_id', models.CharField(max_length=100, verbose_name='Max user ID')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='Уведомления')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Привязан')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='max_link', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связка Max',
                'verbose_name_plural': 'Связки Max',
            },
        ),
    ]
