# Generated by Django 4.2.7 on 2026-07-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_systemsettings_api_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачена'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_warranty',
            field=models.BooleanField(default=False, verbose_name='Гарантийная (бесплатно)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('dispatcher', 'Диспетчер'), ('master', 'Мастер'), ('engineer', 'Инженер'), ('supervisor', 'Руководитель сервисной службы')], default='master', max_length=20, verbose_name='Роль'),
        ),
    ]
