# Generated by Django 4.2.7 on 2026-07-05 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_add_client_max_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('item_type', models.CharField(choices=[('intercom', 'Домофон'), ('video_intercom', 'Видеодомофон'), ('camera', 'Камера'), ('call_panel', 'Вызывная панель'), ('door_lock', 'Дверной замок'), ('monitor', 'Монитор'), ('power_supply', 'Блок питания'), ('cable', 'Кабель'), ('mounting_kit', 'Монтажный комплект'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit', models.CharField(default='шт.', max_length=20, verbose_name='Ед. изм.')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи')),
                ('status', models.CharField(choices=[('in_stock', 'На складе'), ('with_master', 'У мастера'), ('installed', 'Установлено'), ('returned', 'Возвращено'), ('defective', 'Брак'), ('written_off', 'Списано')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место хранения')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Поставщик')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='Гарантия (мес.)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Складская единица',
                'verbose_name_plural': 'Склад',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('online', 'Онлайн')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('is_received', models.BooleanField(default=True, verbose_name='Получено')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.order', verbose_name='Заявка')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('orders_total', models.PositiveIntegerField(default=0, verbose_name='Всего заявок')),
                ('orders_completed', models.PositiveIntegerField(default=0, verbose_name='Выполнено')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка по заявкам')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Комиссия (%)')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Премия')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Удержания')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого к выплате')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён'), ('paid', 'Выплачен')], default='draft', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='main.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Зарплата мастера',
                'verbose_name_plural': 'Зарплаты мастеров',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Приход'), ('out_to_master', 'Выдано мастеру'), ('return_from_master', 'Возврат от мастера'), ('installed', 'Установлено клиенту'), ('return_from_client', 'Возврат от клиента'), ('written_off', 'Списано'), ('defect', 'Брак')], max_length=20, verbose_name='Тип движения')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='main.client', verbose_name='Клиент')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='main.inventoryitem', verbose_name='Оборудование')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='main.master', verbose_name='Мастер')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='main.order', verbose_name='Заявка')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
            ],
            options={
                'verbose_name': 'Движение оборудования',
                'verbose_name_plural': 'Движения оборудования',
                'ordering': ['-created_at'],
            },
        ),
    ]
