# Generated by Django 4.2.7 on 2026-07-05 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_add_roles_and_helpers'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collected_by_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to='main.master', verbose_name='Мастер получил деньги'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collected_by_master_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения денег мастером'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_submitted_to_office',
            field=models.BooleanField(default=False, verbose_name='Сдано в офис'),
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Использован')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inventoryitem', verbose_name='Материал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Материал в заявке',
                'verbose_name_plural': 'Материалы в заявках',
                'unique_together': {('order', 'item')},
            },
        ),
        migrations.CreateModel(
            name='MasterInventoryDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Что нужно сдать')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Возвращено')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('condition', models.CharField(choices=[('working', 'Рабочее'), ('broken', 'Сломанное'), ('repairable', 'Ремонтопригодное')], default='broken', max_length=20, verbose_name='Состояние')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_returns', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_debts', to='main.inventoryitem', verbose_name='Позиция склада')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_debts', to='main.master', verbose_name='Мастер')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_debts', to='main.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Долг по оборудованию',
                'verbose_name_plural': 'Долги по оборудованию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterCashDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('is_paid_to_office', models.BooleanField(default=False, verbose_name='Сдано в кассу')),
                ('paid_to_office_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи в кассу')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_cash', to=settings.AUTH_USER_MODEL, verbose_name='Принял в кассу')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_debts', to='main.master', verbose_name='Мастер')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_debts', to='main.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Долг по наличным',
                'verbose_name_plural': 'Долги по наличным',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='used_materials',
            field=models.ManyToManyField(blank=True, related_name='used_in_orders', through='main.OrderMaterial', to='main.inventoryitem', verbose_name='Материалы'),
        ),
    ]
