# Generated by Django 4.2.7 on 2026-07-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_add_debts_and_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Персональные права'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('dispatcher', 'Диспетчер'), ('master', 'Мастер'), ('installer', 'Монтажник'), ('engineer', 'Инженер'), ('chief_engineer', 'Главный инженер'), ('supervisor', 'Начальник сервисной службы'), ('tech_director', 'Технический директор'), ('executive_director', 'Исполнительный директор'), ('general_director', 'Генеральный директор'), ('clerk', 'Делопроизводитель'), ('accountant', 'Бухгалтер'), ('cashier', 'Кассир'), ('secretary', 'Секретарь')], default='master', max_length=30, verbose_name='Роль'),
        ),
    ]
