# Generated by Django 4.2.7 on 2026-07-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_commercialestimate_estimateservice_legalentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='director_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_legal',
            field=models.BooleanField(default=False, verbose_name='Юридическое лицо'),
        ),
        migrations.AddField(
            model_name='client',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cp_color',
            field=models.CharField(default='#1a3e60', max_length=20, verbose_name='Цвет шапки КП (hex)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cp_footer_text',
            field=models.CharField(blank=True, default='С уважением, команда Видео Сервис', max_length=500, verbose_name='Текст в подвале КП'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cp_header_text',
            field=models.CharField(blank=True, default='Коммерческое предложение', max_length=300, verbose_name='Заголовок КП'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cp_logo_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Логотип для КП (URL)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cp_show_logo',
            field=models.BooleanField(default=True, verbose_name='Показывать логотип'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cp_signature_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО подписанта'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cp_signature_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность подписанта'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cp_validity_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Срок действия КП (дней)'),
        ),
    ]
