# Generated by Django 4.2.7 on 2026-07-07 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_add_supply_chain_and_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает получения'), ('received', 'Получено сотрудником'), ('partially_used', 'Частично использовано'), ('fully_used', 'Полностью использовано'), ('returned', 'Возвращено на склад')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_orders', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_orders', to='main.master', verbose_name='Сотрудник')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_orders', to='main.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Расходный ордер',
                'verbose_name_plural': 'Расходные ордера',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает закупки'), ('ordered', 'Заказано поставщику'), ('received', 'Получено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='main.commercialestimate', verbose_name='Основание (КП/смета)')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='main.order', verbose_name='Основание (заявка)')),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit', models.CharField(default='шт.', max_length=20, verbose_name='Ед. изм.')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ожидаемая цена')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='main.inventoryitem', verbose_name='Номенклатура (если есть в каталоге)')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.purchaserequest', verbose_name='Заявка на закупку')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Позиция заявки на закупку',
                'verbose_name_plural': 'Позиции заявок на закупку',
            },
        ),
        migrations.CreateModel(
            name='IssueOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.PositiveIntegerField(default=0, verbose_name='Выдано')),
                ('quantity_used', models.PositiveIntegerField(default=0, verbose_name='Использовано (установлено)')),
                ('quantity_returned', models.PositiveIntegerField(default=0, verbose_name='Возвращено')),
                ('need_return_old', models.BooleanField(default=False, verbose_name='Требуется возврат старого')),
                ('old_item_description', models.CharField(blank=True, max_length=300, verbose_name='Что нужно вернуть (старое)')),
                ('old_item_returned', models.BooleanField(default=False, verbose_name='Старое возвращено')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_items', to='main.inventoryitem', verbose_name='Номенклатура')),
                ('issue_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.issueorder', verbose_name='Ордер')),
            ],
            options={
                'verbose_name': 'Позиция ордера',
                'verbose_name_plural': 'Позиции ордера',
            },
        ),
    ]
