# Generated by Django 4.2.7 on 2026-07-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_add_issue_order_and_purchase_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_update_enabled',
            field=models.BooleanField(default=False, verbose_name='Автообновление'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='current_version',
            field=models.CharField(default='1.0.0', max_length=50, verbose_name='Текущая версия'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='git_branch',
            field=models.CharField(default='main', max_length=100, verbose_name='Ветка'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='git_repo_url',
            field=models.CharField(blank=True, default='https://github.com/himik19872/videoservice-crm.git', max_length=500, verbose_name='GitHub репозиторий'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='git_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='GitHub токен (для приватных репо)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='last_update_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='latest_commit',
            field=models.CharField(blank=True, max_length=40, verbose_name='Последний коммит'),
        ),
    ]
