# Generated by Django 4.2.7 on 2026-07-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_add_client_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: A-03-12', max_length=50, unique=True, verbose_name='Код места')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Штрихкод места')),
                ('zone', models.CharField(blank=True, help_text='Например: Склад А, Основной', max_length=100, verbose_name='Зона')),
                ('rack', models.CharField(blank=True, help_text='Номер стеллажа', max_length=50, verbose_name='Стеллаж')),
                ('shelf', models.CharField(blank=True, help_text='Номер полки', max_length=50, verbose_name='Полка')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Макс. кол-во позиций (0 = не ограничено)', verbose_name='Вместимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Место хранения',
                'verbose_name_plural': 'Места хранения',
                'ordering': ['zone', 'rack', 'shelf'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.storagelocation', verbose_name='Ячейка хранения'),
        ),
    ]
