# Generated by Django 4.2.7 on 2026-07-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_add_outgoing_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoinginvoiceitem',
            name='vat_rate',
            field=models.CharField(blank=True, default='20%', max_length=10, verbose_name='Ставка НДС'),
        ),
    ]
