# Generated by Django 4.2.7 on 2026-07-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_add_bitrix24_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('manual', 'Ручной ввод'), ('excel_import', 'Импорт Excel (ТСЖ)'), ('erc', 'ЕРЦ'), ('bitrix24', 'Битрикс24')], default='manual', max_length=20, verbose_name='Источник'),
        ),
    ]
