# Generated by Django 4.2.7 on 2026-07-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_add_call_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='asterisk_active',
            field=models.BooleanField(default=False, verbose_name='Интеграция с Asterisk активна'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='asterisk_host',
            field=models.CharField(blank=True, default='192.168.1.68', max_length=100, verbose_name='Asterisk хост'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='asterisk_port',
            field=models.PositiveIntegerField(default=5038, verbose_name='Asterisk AMI порт'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='asterisk_secret',
            field=models.CharField(blank=True, default='crm_asterisk_secret_2026', max_length=255, verbose_name='AMI пароль'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='asterisk_user',
            field=models.CharField(blank=True, default='crm_admin', max_length=100, verbose_name='AMI пользователь'),
        ),
    ]
