# Generated by Django 4.2.7 on 2026-07-10 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_add_asterisk_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsteriskIvr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название IVR')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('greeting_audio', models.CharField(blank=True, help_text='Путь к файлу, напр. /var/lib/asterisk/sounds/ivr/welcome', max_length=200, verbose_name='Аудио приветствия')),
                ('timeout', models.PositiveIntegerField(default=5, verbose_name='Таймаут ввода (сек)')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Макс. попыток')),
                ('invalid_audio', models.CharField(blank=True, max_length=200, verbose_name='Аудио при ошибке')),
                ('exit_destination', models.CharField(default='hangup', help_text='hangup, SIP/101, queue-support', max_length=200, verbose_name='Куда направить при ошибке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Голосовое меню (IVR)',
                'verbose_name_plural': 'Голосовые меню (IVR)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AsteriskTrunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр. rostel-sip, mgts', max_length=80, verbose_name='Название транка')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='Провайдер')),
                ('host', models.CharField(help_text='sip.provider.ru', max_length=200, verbose_name='Сервер провайдера')),
                ('port', models.PositiveIntegerField(default=5060, verbose_name='Порт')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Логин (username)')),
                ('secret', models.CharField(blank=True, max_length=100, verbose_name='Пароль')),
                ('auth_username', models.CharField(blank=True, help_text='Если отличается от username', max_length=100, verbose_name='Auth username')),
                ('from_user', models.CharField(blank=True, max_length=100, verbose_name='From User')),
                ('from_domain', models.CharField(blank=True, max_length=200, verbose_name='From Domain')),
                ('caller_id', models.CharField(blank=True, help_text='Исходящий номер', max_length=100, verbose_name='Caller ID')),
                ('context', models.CharField(default='inbound', max_length=80, verbose_name='Входящий контекст')),
                ('transport', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tls', 'TLS')], default='udp', max_length=10, verbose_name='Транспорт')),
                ('codecs', models.CharField(default='ulaw,alaw', max_length=100, verbose_name='Кодеки')),
                ('max_channels', models.PositiveIntegerField(default=10, verbose_name='Макс. каналов')),
                ('register', models.BooleanField(default=True, help_text='Отправить REGISTER провайдеру', verbose_name='Регистрироваться')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'SIP-транк',
                'verbose_name_plural': 'SIP-транки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AsteriskVoicemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(help_text='Напр. 101@default', max_length=50, verbose_name='Номер ящика')),
                ('password', models.CharField(default='0000', max_length=20, verbose_name='Пароль доступа')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Отображаемое имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email для уведомлений')),
                ('email_attachment', models.BooleanField(default=True, verbose_name='Отправлять запись на email')),
                ('delete_after_email', models.BooleanField(default=False, verbose_name='Удалять после отправки')),
                ('max_messages', models.PositiveIntegerField(default=100, verbose_name='Макс. сообщений')),
                ('max_seconds', models.PositiveIntegerField(default=120, verbose_name='Макс. длительность (сек)')),
                ('min_seconds', models.PositiveIntegerField(default=3, verbose_name='Мин. длительность (сек)')),
                ('greeting', models.CharField(blank=True, help_text='Напр. vm-intro', max_length=200, verbose_name='Приветствие (аудио)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voicemail', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Автоответчик',
                'verbose_name_plural': 'Автоответчики',
                'ordering': ['mailbox'],
            },
        ),
        migrations.CreateModel(
            name='AsteriskSipPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр. 101, 102, manager', max_length=80, verbose_name='Номер/имя')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Отображаемое имя')),
                ('secret', models.CharField(default='', max_length=100, verbose_name='Пароль')),
                ('host', models.CharField(default='dynamic', help_text='dynamic — любой IP, либо фиксированный', max_length=15, verbose_name='Хост')),
                ('transport', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tls', 'TLS')], default='udp', max_length=10, verbose_name='Транспорт')),
                ('codecs', models.CharField(choices=[('ulaw,alaw', 'G.711 (ulaw + alaw)'), ('ulaw,alaw,g722', 'HD Voice (G.722)'), ('ulaw,alaw,gsm', 'G.711 + GSM'), ('opus,ulaw,alaw', 'Opus + G.711')], default='ulaw,alaw', max_length=100, verbose_name='Кодеки')),
                ('context', models.CharField(default='internal', max_length=80, verbose_name='Контекст')),
                ('caller_id', models.CharField(blank=True, help_text='Отображаемый номер, напр. +74951112233', max_length=100, verbose_name='Caller ID')),
                ('mailbox', models.CharField(blank=True, help_text='Напр. 101@default', max_length=50, verbose_name='Голосовая почта')),
                ('nat', models.BooleanField(default=True, verbose_name='NAT (за роутером)')),
                ('allow', models.CharField(default='ulaw,alaw', max_length=200, verbose_name='Разрешённые кодеки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_peer', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'SIP-аккаунт',
                'verbose_name_plural': 'SIP-аккаунты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AsteriskRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название маршрута')),
                ('direction', models.CharField(choices=[('inbound', 'Входящий'), ('outbound', 'Исходящий'), ('internal', 'Внутренний')], max_length=20, verbose_name='Направление')),
                ('match_pattern', models.CharField(choices=[('_X.', 'Любой номер'), ('_8XXXXXXXXXX', 'Местный (8XXXXXXXXXX)'), ('_+7XXXXXXXXXX', 'Мобильный (+7XXXXXXXXXX)'), ('_8XXXXXXXXXXX', 'Мобильный (8XXXXXXXXXXX)'), ('_XXXX', 'Внутренний (короткий)')], default='_X.', max_length=80, verbose_name='Шаблон номера')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Приоритет')),
                ('prepend', models.CharField(blank=True, help_text='Напр. 8, +7, 810', max_length=20, verbose_name='Добавить перед номером')),
                ('strip', models.PositiveIntegerField(default=0, help_text='Сколько цифр убрать из номера', verbose_name='Убрать цифр сначала')),
                ('destination', models.CharField(blank=True, help_text='Куда направить: SIP/101, ivr-main, queue-support', max_length=200, verbose_name='Цель (extension/context)')),
                ('caller_id_override', models.CharField(blank=True, max_length=100, verbose_name='Подмена Caller ID')),
                ('failover_destination', models.CharField(blank=True, help_text='Куда направить при отказе', max_length=200, verbose_name='Резервная цель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('trunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='main.asterisktrunk', verbose_name='Транк')),
            ],
            options={
                'verbose_name': 'Маршрут звонков',
                'verbose_name_plural': 'Маршруты звонков',
                'ordering': ['direction', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='AsteriskIvrOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.CharField(help_text='0-9, *, # или t (таймаут)', max_length=5, verbose_name='Цифра')),
                ('action', models.CharField(choices=[('extension', 'Внутренний номер'), ('queue', 'Очередь'), ('ivr', 'Под-меню (IVR)'), ('playback', 'Проиграть аудио'), ('voicemail', 'Голосовая почта'), ('hangup', 'Завершить звонок'), ('dial', 'Набрать номер')], default='extension', max_length=20, verbose_name='Действие')),
                ('destination', models.CharField(help_text='SIP/101, queue-support, hangup, номер', max_length=200, verbose_name='Цель')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание (озвучка)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('ivr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.asteriskivr', verbose_name='IVR')),
            ],
            options={
                'verbose_name': 'Опция IVR',
                'verbose_name_plural': 'Опции IVR',
                'ordering': ['ivr', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AsteriskCallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True, verbose_name='ID звонка')),
                ('caller', models.CharField(max_length=50, verbose_name='Звонящий')),
                ('callee', models.CharField(max_length=50, verbose_name='Вызываемый')),
                ('direction', models.CharField(choices=[('incoming', 'Входящий'), ('outgoing', 'Исходящий'), ('internal', 'Внутренний')], max_length=20, verbose_name='Направление')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Синхронизировано')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_recordings', to='main.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Запись звонка',
                'verbose_name_plural': 'Записи звонков',
                'ordering': ['-start_time'],
            },
        ),
    ]
