# Generated by Django 4.2.7 on 2026-07-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_add_asterisk_telephony'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='asterisk_ssh_password',
            field=models.CharField(blank=True, default='96811621', max_length=255, verbose_name='SSH пароль'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='asterisk_ssh_port',
            field=models.PositiveIntegerField(default=22, verbose_name='SSH порт'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='asterisk_ssh_user',
            field=models.CharField(blank=True, default='himik', max_length=100, verbose_name='SSH пользователь'),
        ),
    ]
