# Generated by Django 4.2.7 on 2026-07-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_add_asterisk_ssh_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='district',
            field=models.CharField(blank=True, max_length=200, verbose_name='Район / пригород'),
        ),
        migrations.AddField(
            model_name='building',
            name='equipment_list',
            field=models.TextField(blank=True, verbose_name='Список оборудования'),
        ),
        migrations.AddField(
            model_name='building',
            name='liter',
            field=models.CharField(blank=True, max_length=10, verbose_name='Литера'),
        ),
        migrations.AddField(
            model_name='building',
            name='management_company',
            field=models.CharField(blank=True, max_length=300, verbose_name='Управляющая компания / ТСЖ'),
        ),
        migrations.AddField(
            model_name='building',
            name='programming_code',
            field=models.CharField(blank=True, max_length=200, verbose_name='Код программирования'),
        ),
        migrations.AddField(
            model_name='client',
            name='apartment',
            field=models.CharField(blank=True, max_length=20, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='client',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='main.building', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='client',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Корпус/строение'),
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(default='Санкт-Петербург', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес (строка)'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['city', 'street_name', 'house_number'], name='main_buildi_city_4fc38b_idx'),
        ),
    ]
