# Generated by Django 4.2.7 on 2026-07-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_add_client_contract_and_tariffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='entrance_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='entrance_str',
        ),
        migrations.RemoveField(
            model_name='client',
            name='management_company_str',
        ),
        migrations.AddField(
            model_name='buildingentrance',
            name='access_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код открытия двери'),
        ),
        migrations.AddField(
            model_name='buildingentrance',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='IP-адрес панели'),
        ),
        migrations.AddField(
            model_name='buildingentrance',
            name='programming_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код программирования ключей'),
        ),
        migrations.CreateModel(
            name='BewardDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='Район')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('entrance_number', models.CharField(blank=True, max_length=10, verbose_name='Номер подъезда')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP-адрес')),
                ('access_code', models.CharField(blank=True, max_length=50, verbose_name='Код открытия двери')),
                ('programming_code', models.CharField(blank=True, max_length=50, verbose_name='Код программирования ключей')),
                ('door_opening_code', models.CharField(blank=True, max_length=50, verbose_name='Код открытия двери (доп.)')),
                ('apartment_range', models.CharField(blank=True, max_length=100, verbose_name='Нумерация квартир')),
                ('date_issued', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи ключей')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beward_devices', to='main.building', verbose_name='Привязанный дом')),
                ('entrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beward_devices', to='main.buildingentrance', verbose_name='Привязанный подъезд')),
            ],
            options={
                'verbose_name': 'Панель Beward',
                'verbose_name_plural': 'Панели Beward (справочник IP)',
                'ordering': ['address', 'entrance_number'],
            },
        ),
    ]
