# Generated by Django 4.2.7 on 2026-07-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_beward_device_and_entrance_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewarddevice',
            name='entrance_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер подъезда'),
        ),
    ]
