# Generated by Django 4.2.7 on 2026-07-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_beward_entrance_number_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewarddevice',
            name='access_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код открытия двери'),
        ),
        migrations.AlterField(
            model_name='bewarddevice',
            name='door_opening_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код открытия двери (доп.)'),
        ),
        migrations.AlterField(
            model_name='bewarddevice',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='bewarddevice',
            name='programming_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код программирования ключей'),
        ),
        migrations.AlterField(
            model_name='buildingentrance',
            name='access_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код открытия двери'),
        ),
        migrations.AlterField(
            model_name='buildingentrance',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='IP-адрес панели'),
        ),
        migrations.AlterField(
            model_name='buildingentrance',
            name='programming_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код программирования ключей'),
        ),
    ]
