# Generated by Django 4.2.7 on 2026-07-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_beward_field_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompany',
            name='payment_method',
            field=models.CharField(choices=[('contract', 'По договору с УК/ТСЖ'), ('erc', 'Через ЕРЦ (прямые платежи жителей)'), ('mixed', 'Смешанная')], default='contract', max_length=20, verbose_name='Способ оплаты за домофон'),
        ),
    ]
