# Generated by Django 4.2.7 on 2026-07-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_mc_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='management_company_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings_list', to='main.managementcompany', verbose_name='УК/ТСЖ (справочник)'),
        ),
        migrations.CreateModel(
            name='BuildingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('intercom', 'Домофон'), ('cctv', 'Видеонаблюдение'), ('access_control', 'СКУД'), ('dispatch', 'Диспетчеризация'), ('auskue', 'АУСКУЭ'), ('gate', 'Ворота'), ('barrier', 'Шлагбаум'), ('fire_alarm', 'Пожарная сигнализация'), ('elevator_dispatch', 'Диспетчеризация лифтов'), ('other', 'Другое')], max_length=30, verbose_name='Тип системы')),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма в месяц')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='main.building', verbose_name='Дом')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Система дома',
                'verbose_name_plural': 'Системы домов',
                'ordering': ['building', 'system_type'],
                'unique_together': {('building', 'system_type')},
            },
        ),
    ]
