# Generated by Django 4.2.7 on 2026-07-19 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_mc_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_orders', to='main.order', verbose_name='Главная заявка (объединение)'),
        ),
    ]
