# Generated by Django 4.2.7 on 2026-07-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_parent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='dadata_verified',
            field=models.BooleanField(default=False, verbose_name='Адрес проверен через Dadata'),
        ),
    ]
