# Generated by Django 4.2.7 on 2026-07-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_add_dadata_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['code'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AddField(
            model_name='building',
            name='is_dormitory',
            field=models.BooleanField(default=False, help_text='В одной квартире может быть несколько лицевых счетов', verbose_name='Общежитие'),
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(default='', help_text='Напр. 78 (СПб), 47 (ЛО), 77 (Москва)', max_length=3, verbose_name='Код региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.CharField(default='Россия', max_length=100, verbose_name='Страна'),
        ),
    ]
