# Generated by Django 4.2.7 on 2026-07-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_add_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку для умерших/съехавших — они исключаются из статистики', verbose_name='Активен'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер квартиры')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='main.building', verbose_name='Дом')),
                ('entrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='main.buildingentrance', verbose_name='Подъезд')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['building', 'number'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='apartment_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='main.apartment', verbose_name='Квартира (объект)'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['building', 'number'], name='main_apartm_buildin_c22de6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('building', 'number')},
        ),
    ]
