# Generated by Django 4.2.7 on 2026-07-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_add_apartment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='management_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.managementcompany', verbose_name='Управляющая компания'),
        ),
    ]
