# Generated by Django 4.2.7 on 2026-07-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_add_order_management_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialestimate',
            name='management_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='main.managementcompany', verbose_name='Управляющая компания'),
        ),
    ]
