# Generated by Django 4.2.7 on 2026-07-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_make_order_client_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10, verbose_name='Платформа')),
                ('version', models.CharField(help_text='Например: 1.2.3', max_length=20, verbose_name='Версия (semver)')),
                ('version_code', models.PositiveIntegerField(default=1, verbose_name='Код версии (build number)')),
                ('changelog', models.TextField(blank=True, verbose_name='Что нового')),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='app/', verbose_name='APK/IPA файл')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('file_hash', models.CharField(blank=True, max_length=64, verbose_name='SHA256 хеш файла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное обновление')),
                ('min_android_version', models.CharField(default='5.0', max_length=10, verbose_name='Мин. версия Android')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Версия приложения',
                'verbose_name_plural': 'Версии приложения',
                'ordering': ['-version_code'],
                'unique_together': {('platform', 'version_code')},
            },
        ),
    ]
