# Generated by Django 4.2.7 on 2026-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_add_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='cp_logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип (файл)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cp_signature_file',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Подпись (файл)'),
        ),
    ]
