# Generated by Django 4.2.7 on 2026-07-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_add_cp_logo_signature_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='tax_system',
            field=models.CharField(choices=[('usn', 'УСН (доходы)'), ('usn_dr', 'УСН (доходы-расходы)'), ('osno', 'ОСНО (с НДС)'), ('patent', 'Патент'), ('none', 'Без налога')], default='usn', max_length=10, verbose_name='Система налогообложения'),
        ),
    ]
