# Generated by Django 4.2.7 on 2026-07-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_add_tax_system_to_legal_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialestimate',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='В т.ч. НДС'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='vat_rate',
            field=models.DecimalField(decimal_places=1, default=0, help_text='0 — без НДС, 20 — 20%, 10 — 10%', max_digits=4, verbose_name='Ставка НДС (%)'),
        ),
    ]
