# Generated by Django 4.2.7 on 2026-07-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_add_vat_and_total_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialestimate',
            name='total_ugol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма угля (откат)'),
        ),
        migrations.AddField(
            model_name='commercialestimate',
            name='ugol_apply_to',
            field=models.CharField(choices=[('all', 'На все позиции'), ('selected', 'Только выбранные')], default='all', max_length=10, verbose_name='Применять уголь'),
        ),
        migrations.AddField(
            model_name='commercialestimate',
            name='ugol_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить уголь (откат)'),
        ),
        migrations.AddField(
            model_name='commercialestimate',
            name='ugol_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент угля (%)'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='ugol_applied',
            field=models.BooleanField(default=False, verbose_name='Уголь применён к позиции'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='cp_color',
            field=models.CharField(blank=True, default='#1a3e60', max_length=20, verbose_name='Цвет шапки КП (hex)'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='cp_footer_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текст в подвале КП'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='cp_header_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заголовок КП'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='cp_logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='legal_entity_logos/', verbose_name='Логотип (файл)'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='cp_show_logo',
            field=models.BooleanField(default=True, verbose_name='Показывать логотип'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='cp_signature_file',
            field=models.ImageField(blank=True, null=True, upload_to='legal_entity_signatures/', verbose_name='Подпись (файл)'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='cp_signature_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО подписанта'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='cp_signature_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность подписанта'),
        ),
    ]
