# Generated by Django 4.2.7 on 2026-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_commercialestimate_total_ugol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialestimate',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Комиссионные (₽)'),
        ),
        migrations.AddField(
            model_name='commercialestimate',
            name='cost_materials',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себест. материалов'),
        ),
        migrations.AddField(
            model_name='commercialestimate',
            name='cost_services',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себест. работ'),
        ),
        migrations.AddField(
            model_name='commercialestimate',
            name='dealer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Дилерская наценка (₽)'),
        ),
    ]
