# Generated by Django 4.2.7 on 2026-07-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_commercialestimate_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='cp_show_signature',
            field=models.BooleanField(default=True, verbose_name='Показывать подпись'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='cp_show_signature',
            field=models.BooleanField(default=True, verbose_name='Показывать подпись'),
        ),
    ]
