# Generated by Django 4.2.7 on 2026-07-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_legalentity_cp_show_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_available_from',
            field=models.TimeField(default='09:00', verbose_name='Клиент доступен с'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_available_to',
            field=models.TimeField(default='18:00', verbose_name='Клиент доступен до'),
        ),
    ]
