# Generated by Django 4.2.7 on 2026-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_order_client_available_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('category', models.CharField(choices=[('equipment', 'Оборудование'), ('installation', 'Монтаж'), ('setup', 'Настройка'), ('repair', 'Ремонт'), ('safety', 'Техника безопасности'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('pdf_file', models.FileField(upload_to='instructions/', verbose_name='PDF-файл')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
                'ordering': ['category', 'order_num', 'title'],
            },
        ),
    ]
