# Generated by Django 4.2.7 on 2026-08-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='pdf_file',
            field=models.FileField(upload_to='instructions/', verbose_name='Файл (PDF, JPG, PNG)'),
        ),
    ]
