# Generated by Django 4.2.7 on 2026-08-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_instruction_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueorderitem',
            name='source_type',
            field=models.CharField(choices=[('warehouse', 'Со склада'), ('master_zip', 'Из ЗИП мастера')], default='warehouse', max_length=20, verbose_name='Источник выдачи'),
        ),
    ]
