# Generated by Django 4.2.7 on 2026-08-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_issueorderitem_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueorderitem',
            name='source_type',
        ),
        migrations.AddField(
            model_name='issueorderitem',
            name='source',
            field=models.CharField(choices=[('warehouse', 'Со склада'), ('master_zip', 'Из ЗИПа мастера')], default='warehouse', max_length=15, verbose_name='Источник выдачи'),
        ),
    ]
