# Generated by Django 4.2.7 on 2026-08-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_remove_issueorderitem_source_type_and_more'),
    ]

    operations = [
    ]
