# Generated by Django 4.2.7 on 2026-08-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_issue_order_source'),
    ]

    operations = [
    ]
