# Generated by Django 4.2.7 on 2026-07-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_building_order_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принята'),
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='order',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='На паузе'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('cashless', 'Безналичные')], max_length=10, null=True, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='photo_report_required',
            field=models.BooleanField(default=False, verbose_name='Требуется фото/видео отчёт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('assigned', 'Назначена'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('paused', 'На паузе'), ('need_help', 'Требуется помощь'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
