# Generated by Django 4.2.7 on 2026-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_add_client_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.CharField(blank=True, max_length=200, verbose_name='Район (муниципальный)'),
        ),
    ]
