# Generated by Django 4.2.7 on 2026-07-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_client_account_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
